server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/share
    username : root
    password : libin1996
    driverClassName : com.mysql.jdbc.Driver
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5
  mybatis:
    mapper-locations: classpath:com/example/demo/mapper/*.xml
